### ISSUE TITLE
jdk8 hotspot nightly binaries not being returned by v3 api

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-api-v3#112]
https://api.adoptopenjdk.net/v3/binary/latest/8/ea/linux/x64/jdk/hotspot/normal/adoptopenjdk is not returning a jdk binary as expected.

**Comment by johnoliver** [comment]
This is probably related to the fact that the latest nightly did not contain a binary of that type:

https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u-2020-02-06-13-39

But even so, that is not behaviour that we should expect
