### ISSUE TITLE
Latest nightly builds not returned by API

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-api-v3#117]
The latest nightly builds are not returned by the v3 api:
Running:
```
https://api.adoptopenjdk.net/v3/binary/latest/8/ea/aix/ppc64/jdk/openj9/normal/adoptopenjdk
```
returns the build from the 6th Feb
```
OpenJDK8U-jdk_ppc64_aix_openj9_2020-02-06-13-39.tar.gz
```
even though there are later builds available - e.g. these builds are from 12th Feb: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u-2020-02-12-20-33

The nightly builds download page also shows 6th Feb as being the latest available builds (presumably it uses the api): https://adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9

**Comment by johnoliver** [comment]
@lumpfish probably related to #116 the current builds being produced have the version `8.0.242` where as older builds had `8.0.252` which means they are more recent

**Comment by lumpfish** [comment]
This affects jdk11 as well as jdk8.  jdk8 appear to be fixed, not jdk11.

It seems like we need a definition of 'latest', or perhaps two different 'latests' - latest version of code used or latest build to be built.  Certainly users should understand the basis on which build are being displayed.
