### ISSUE TITLE
v3 API should be able to retrieve testimage artifacts for a certain release

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-api-v3#12]
`Binary Type` already has `jre` and `jdk` as possible values. A third possible value of `testimage` comes to mind for retrieving the test image which can then be used for testing.

PR adding testimage artifacts:
https://github.com/AdoptOpenJDK/openjdk-build/pull/1251

Examples:
https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/133/
https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/tag/jdk-11.0.5%2B5

Note: `testimage` artifacts are JDK 11+ only.

**Comment by johnoliver** [comment]
should be working
