### ISSUE TITLE
Nightly releases do not contain a single version

### ISSUE THREAD

**Issue by johnoliver** [AdoptOpenJDK/openjdk-api-v3#120]
The current schema assumes that a given release contains releases of the same version. In fact we have a mix of versions inside nightlies.

## Solution 1

Break api and move the version from the high level release object and onto the individual binary object. This is not great in general breaking backwards compatibility and would also probably complicate peoples handling logic.

## Solution 2

Group binaries by version and return a release for each group, i.e if a release contains versions `11.0.7+1`, `11.0.7+2` and `11.0.7+3`. It would return 3 release objects one for each version.

Main issue with this is probably the `id` field that is on the Release people may have assumed that this would be a unique id, if we were to return 3 releases one for each version, all of them would have the same id. I doubt this would be a problem as I am not sure people will have treated the id in this way. Solution to the `id` problem would be either just have duplicate ids or remove the id field completely, between those I think I would go for having duplicate ids.

**Comment by sxa555** [comment]
Can you link to a release which shows this? I'm not clear at the moment on how a nightly would end up with different versions ... Come to think of it what do you mean by "version" here?

**Comment by johnoliver** [comment]
@sxa555 if you look at:

https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk11u-2020-02-21-17-42

in that nighty, aarch is at `11.0.7+2`, mac openj9 is at `11.0.7+3`

**Comment by sxa555** [comment]
Even on aarch64, [openj9](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2020-02-21-17-42/OpenJDK11U-jdk_aarch64_linux_openj9_linuxXL_2020-02-21-17-42.tar.gz.json) is 11.0.7+3 but [hotspot](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2020-02-21-17-42/OpenJDK11U-jdk_aarch64_linux_hotspot_2020-02-21-17-42.tar.gz.json) is 11.0.7+2

**Comment by sxa555** [comment]
@andrew-m-leonard Any idea why hotspot and openj9 are showing different versions?

**Comment by andrew-m-leonard** [comment]
@sxa this is expected, as Nightlies for OpenJ9 build the level of openjdk in the "Extensions" repo, whereas Hotspot builds the level from the Adopt hg-git mirror...

**Comment by sxa555** [comment]
This is exposing an underlying bug -  HotSpot is still locked at 11.0.7+2, but the OpenJ9 builds are correctly building 11.0.7+5. Raised at https://github.com/AdoptOpenJDK/openjdk-build/issues/1584

Saying that, OpenJ9 have a bit of extra process before new merges are committed into the repositories so we need to be able to handle the case where they can get slightly out of sync

**Comment by karianna** [comment]
Solution 1 would warrant a v4 API no doubt.  I'm not sure I'm happy with Solution 2 either (I expect id's to be unique).  I don't have a good answer here, just musing

**Comment by andrew-m-leonard** [comment]
Maybe:
Solution 3) Since we already name "GA Releases" differently for different vendors/variant, eg."jdk-11.0.6+10_openj9-0.18.1", perhaps we should do the same for "Nightlies". As this problem is just going to get bigger, for example with Corretto added we are in no control over what level of OpenJDK they have in their github... So something like:
- jdk11u-2020-03-09-03-07_Hotspot
- jdk11u-2020-03-09-03-07_OpenJ9
- jdk11u-2020-03-09-03-07_Corretto

**Comment by johnoliver** [comment]
Another solution would be for us to append a suffix to the existing id to make them unique again

**Comment by karianna** [comment]
> Another solution would be for us to append a suffix to the existing id to make them unique again

I'd be OK with that.
