### ISSUE TITLE
Make debugimage archives available via the API

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-api-v3#128]
It would be useful to have downloads of the debug image archives via the API. Ideally the debugimage archives will be preserved for every build. 

https://github.com/AdoptOpenJDK/openjdk-build/issues/1596 added debug image archives for OpenJ9 builds. Copying the contained debug-image folder over top of the jdk makes symbols available to greatly ease the task of debugging an issue with native code. 

See also https://github.com/AdoptOpenJDK/openjdk-website/issues/696

**Comment by karianna** [comment]
@johnoliver Happy to have an API design conversation if this doesn't already naturally slot in.

**Comment by johnoliver** [comment]
#130 should do it
