### ISSUE TITLE
Define standard linting rules to automate style-related PR reviews

### ISSUE THREAD

**Issue by ParkerM** [AdoptOpenJDK/openjdk-api-v3#146]
This would automate reviews for most style issues and provide instant PR feedback to contributors, as well as automate some project configuration processes in capable IDE's.  

Seeing as v3 is entering the active development phase, a consensus on standard style rules would prevent a lot of headaches, discussions, and manual intervention for the contributions that lie ahead. 
Common "obvious" inconsistencies such as spacing, semicolon usage, tab width, and continuation width, can be detected in CI by defining them at the error level. Style issues that are debatable or context-dependent can be defined at the warning level to provide visibility for approvers and submitters without halting the pipeline.

Something like Code Climate ([free for OSS](https://codeclimate.com/quality/pricing/)) could be used for more granular control over Travis CI/GitHub integration, as well as lay the foundation for stuff like coverage reports and static analysis. As for Typescript linting, Microsoft appears to be [phasing out TSLint](https://github.com/typescript-eslint/typescript-eslint#what-about-tslint) in favor of ESLint, which is already used by the API and capable of handling some surprisingly complex cases.

I can submit a PR if this is a desirable feature, but wouldn't feel comfortable doing so without some sort of consensus. I'll respond below with a few of my own preferences.

**Comment by gdams** [comment]
fixed by https://github.com/AdoptOpenJDK/openjdk-api-v3/pull/157
