### ISSUE TITLE
ongoing issue with website/v3api not showing latest openj9 releases

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-api-v3#184]
Seem this problem persists, the jdk-11.0.7+10_openj9-0.20.0 MacOSXL build that was publish last night, was still not visible midday today.... George had to manually update the API...
I think we need to get to the bottom of this issue?
Is it anything to do with github rate limiting?

**Comment by chadlwilson** [comment]
I may be misunderstanding the issue here, but this seems to still be a problem for the Mac `11.0.7+10` `hotspot` releases too.

The latest releases appear to be appearing on https://api.adoptopenjdk.net/v3/assets/latest/11/hotspot 

```json
{
        "binary": {
            "architecture": "x64",
            "download_count": 2439,
            "heap_size": "normal",
            "image_type": "jdk",
            "installer": {
                "checksum": "eb2c64c9141f2108b96c473998c661324a6f4853e0e449c8d3c0c464ca2dac2b",
                "checksum_link": "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10/OpenJDK11U-jdk_x64_mac_hotspot_11.0.7_10.pkg.sha256.txt",
                "download_count": 13843,
                "link": "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10/OpenJDK11U-jdk_x64_mac_hotspot_11.0.7_10.pkg",
                "name": "OpenJDK11U-jdk_x64_mac_hotspot_11.0.7_10.pkg",
                "size": 189117558
            },
            "jvm_impl": "hotspot",
            "os": "mac",
            "package": {
                "checksum": "0ab1e15e8bd1916423960e91b932d2b17f4c15b02dbdf9fa30e9423280d9e5cc",
                "checksum_link": "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10/OpenJDK11U-jdk_x64_mac_hotspot_11.0.7_10.tar.gz.sha256.txt",
                "download_count": 2439,
                "link": "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10/OpenJDK11U-jdk_x64_mac_hotspot_11.0.7_10.tar.gz",
                "name": "OpenJDK11U-jdk_x64_mac_hotspot_11.0.7_10.tar.gz",
                "size": 184353243
            },
            "project": "jdk",
            "scm_ref": "jdk-11.0.7+10_adopt",
            "updated_at": "2020-04-15T15:46:39Z"
        },
        "release_name": "jdk-11.0.7+10",
        "version": {
            "adopt_build_number": 1,
            "build": 10,
            "major": 11,
            "minor": 0,
            "openjdk_version": "11.0.7+10",
            "security": 7,
            "semver": "11.0.7+10.1"
        }
    },
```

but not https://api.adoptopenjdk.net/v3/assets/feature_releases/11/ga?architecture=x64&os=mac&image_type=jdk&page=0&page_size=1000&project=jdk&sort_order=ASC&vendor=adoptopenjdk which only shows `11.0.6+10` releases.

Same problem doesn't seem to affect `x64` `linux` releases.

This is causing the releases to be missing downstream for [asdf-java](https://github.com/halcyon/asdf-java/blob/master/bin/functions#L56) which uses this API to discover releases.

**Comment by chadlwilson** [comment]
Actually; found the issue affecting the above - seems there is a hidden (?) max `page_size` of 20 releases [here](https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/811367c50ece18b5b94728ee6d50f3568da6d7c2/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt#L275). Which is causing the more recent releases to fall off the back of the query give the sort is `ASC`. The `page_size=100` in the query is ineffective.

* This doesn't seem to be documented in the Swagger docs.
