### ISSUE TITLE
Add V3 examples to the documentation in addition to just the swagger UI

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-api-v3#186]
Examples will make it easier for people to easily migrate to the V3 API

**Comment by adam-thorpe** [comment]
Examples now in https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/docs/STRUCTURE.md

**Comment by sxa** [comment]
Thanks Adam! Can we get that lnk added to the top level page at https://api.adoptopenjdk.net/ along with the link to the swagger docs?

**Comment by adam-thorpe** [comment]
Swagger docs was already on the page, I've added a link on the README but not sure how that gets updated to the live version

**Comment by sxa** [comment]
Thanks - (That's when I meant - that I wanted a new link to go alongside the /existing/ swagger-ui link that was already there). Where did you make the change?

I've no idea how it goes live either to be honest - @johnoliver ?

**Comment by johnoliver** [comment]
I am not sure what the question is, the README is only displayed in the github repo, and the link to STRUCTURE.md is showing at https://github.com/AdoptOpenJDK/openjdk-api-v3

**Comment by adam-thorpe** [comment]
The page at https://api.adoptopenjdk.net/ shows the exact same content as the README, I thought it might pull from it and use it to display the page but it would seem not. I think this is what Stewart is asking for

**Comment by johnoliver** [comment]
that is at openjdk-api-v3/adoptopenjdk-api-v3-frontend/src/main/resources/META-INF/resources/index.html

**Comment by adam-thorpe** [comment]
Oh wow okay, I'll update it then too

**Comment by nickebbitt** [comment]
I think this issue can be closed, the landing page (https://api.adoptopenjdk.net/) now has a link to the `STRUCTURE.md` document that contains some V3 examples.

**Comment by sxa** [comment]
I'd like to update it a bit further (if you're just looking for examples having it hidden at the bottom isn't ideal) but yes the initial requirement is fundamentally complete so I'm happy to close and enhance later

**Comment by nickebbitt** [comment]
Makes sense. 

It would also be good if we could generate the examples from tests (like [Spring REST Docs](https://spring.io/projects/spring-restdocs)), the benefit being well structured examples that evolve and stay conistent with the codebase.

I'll check out what's possible with Quarkus and create a new issue highlighting any options we have.
