### ISSUE TITLE
v3/binary/latest doesn't give the latest release build

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-api-v3#209]
The following v3 api link doesn't download the "latest" [11.0.7+10.1 build](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10.1_openj9-0.20.0/OpenJDK11U-jdk_ppc64_aix_openj9_11.0.7_10_openj9-0.20.0.tar.gz) but the 11.0.7+10 build

https://api.adoptopenjdk.net/v3/binary/latest/11/ga/aix/ppc64/jdk/openj9/normal/adoptopenjdk

There may be a similar problem for Mac (+10.2) and Windows (+10.1) releases.

**Comment by johnoliver** [comment]
Since at the time of release of 11.0.7+10 the default adopt version number was 1 the version in the 11.0.7+10 metadata file is 11.0.7+10.1 so it would be uncertain which would be chosen to be download. 10.2 will not be effected as there is an ordering for that.
