### ISSUE TITLE
Enhance API to return the latest jdk version number

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-api-v3#212]
Ref https://github.com/AdoptOpenJDK/openjdk-build/pull/1574

https://api.adoptopenjdk.net/v3/info/available_releases does not return the JDK-Next number (currently 15). Enhancing the API to add a `latest_jdk_version` attribute and accompanying version number would be sufficient to reopen 1574.

**Comment by dreis2211** [comment]
I'd like to extend that request to make sure that the other APIs understand this latest version as well. In this particular case 15 should be a valid input for EA builds in `/v3/assets/feature_releases/{feature_version}/{release_type}`

**Comment by johnoliver** [comment]
Having looked at the definitions for `info/available_releases` it strikes me that we have not actually documented what the fields mean, how do people feel about the descriptions given below:

```
    @Schema(example = "[8,9,10,11,12,13,14,15]", description = "The versions for which adopt have produced a ga release")
    val available_releases: Array<Int>

    @Schema(example = "[8,11]", description = "The lts versions for which adopt have produced a ga release")
    val available_lts_releases: Array<Int>

    @Schema(example = "11", description = "The highest lts version for which adopt have produced a ga release")
    val most_recent_lts: Int

    @Schema(example = "13", description = "The highest version (lts or not) for which adopt have produced a ga release")
    val most_recent_feature_release: Int

    @Schema(example = "15", description = "The highest version (lts or not) for which we have produced a build, this may be a version that has not yet produced a ga release")
    val most_recent_feature_version: Int

    @Schema(example = "15", description = "The version that is currently in development at openjdk")
    val tip_version: Int
```

**Comment by johnoliver** [comment]
I have included there the 2 new fields most_recent_feature_version and tip_version that I would propose to address this issue

**Comment by dreis2211** [comment]
@johnoliver 

```
    @Schema(example = "[8,9,10,11,12,13,14,15]", description = "The versions for which adopt have produced a ga release")
    val available_releases: Array<Int>
```

15 wouldn't be a GA release, but rather an EA release, right? That wouldn't match the description.

**Comment by johnoliver** [comment]
Yea that is just an example so will be true at some point, but can be removed
