### ISSUE TITLE
Latest JDK14 nightly builds are from May 8

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-api-v3#213]
Looking at https://adoptopenjdk.net/nightly.html?variant=openjdk14&jvmVariant=openj9 the latest nightly builds are from May 8. Same with hotspot.

**Comment by johnoliver** [comment]
This is caused by us now defaulting the adopt build number to 0 rather than 1, as a result the older nightlies have a higher build number due to that change
