### ISSUE TITLE
/info/available_releases includes 15, but the API returns 404 when using 15

### ISSUE THREAD

**Issue by ingokegel** [AdoptOpenJDK/openjdk-api-v3#219]
Since today, 

https://api.adoptopenjdk.net/v3/info/available_releases 

includes 15, but the API returns 404 for other operations for 15, for example for

https://api.adoptopenjdk.net/v3/assets/feature_releases/15/ga

**Comment by karianna** [comment]
@johnoliver is this a dup of #217 ?

**Comment by johnoliver** [comment]
@karianna  yes
