### ISSUE TITLE
Track user-agent in API requests so we know how people are using it

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-api-v3#220]
I've mentioned this before but apparently haven't opened an issue on it. If possible it would be very useful to track how many requests are coming into the API via browsers, command line tools such as `wget` or other automatic install toolks like Chocolaty etc.

If we could have logs of the user-agent on each API download call that would be useful to see how many of our downloads are automated tools that people are using and how many are people just downloading using a browser.

**Comment by nickebbitt** [comment]
did I see somewhere that we use CloudFlare to front the API? if so then the CloudFlare request logs, if we can get access to them, will contain this information so that could be an option

**Comment by karianna** [comment]
@johnoliver was looking at this.

**Comment by johnoliver** [comment]
In the staging branch they are tracked

**Comment by sxa** [comment]
@johnoliver Is that going to get into master?
