### ISSUE TITLE
Add Linux/riscv to the platforms available through the API (and website!)

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-api-v3#224]
These are available from the main pipelines at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-riscv64-openj9/ but are not currently being published on the nightlies page at https://adoptopenjdk.net/archive.html?variant=openjdk11&jvmVariant=openj9

Note; We've had to fake up `java -version` output due to cross compiling on this platform (https://github.com/AdoptOpenJDK/openjdk-build/pull/1762/files). This may have an impact on how the the API deals with this platform (If it's a problem we'll need a solution to https://github.com/AdoptOpenJDK/openjdk-build/issues/1773 first)

**Comment by adam-thorpe** [comment]
Looking into this, shouldn't be too hard I imagine

**Comment by sxa** [comment]
Thanks for picking this up Adam. I wouldn't expect it to be too tricky once you know your way around, but it'll be a good opportunity to document how to do it in a FAQ for future platforms :-)

**Comment by gdams** [comment]
@adam-thorpe can this be closed now that #229 has landed?

**Comment by adam-thorpe** [comment]
Yes I'll close it now, changes should be visible on the website when staging gets merged
