### ISSUE TITLE
Make configure_arguments available in the API

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-api-v3#235]
See https://github.com/AdoptOpenJDK/openjdk-build/issues/11

This may also be an api issue but we are now adding the bash configure output to the metadata from the builds. Assuming this will now automatically appear in the API, please provide this output on the download so users who are curious can see how exactly our binaries are built

**Comment by johnoliver** [comment]
we are going to look at adding a link to the metadata file into the api on the Asset, so people that are interested in the configure arguments can follow that link

**Comment by nickebbitt** [comment]
I've started looking at this

**Comment by M-Davies** [comment]
@nickebbitt Can this be closed?

**Comment by nickebbitt** [comment]
@M-Davies the change was merged to `staging` but not yet `master` - not sure what the process is but the work is done but not yet released to live.

**Comment by karianna** [comment]
@johnoliver Can you release to master?  I guess we can then advertise this out and enable it in the website as well.

**Comment by nickebbitt** [comment]
@karianna this now live so can be closed

**Comment by M-Davies** [comment]
Same with https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/236, I recommend that this is shifted back over to the openjdk-website repo as some work will need to be done over there to expose the metadata

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-website/issues/786
