### ISSUE TITLE
Add java -version output to the nightly build download page

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-api-v3#236]
See https://github.com/AdoptOpenJDK/openjdk-build/issues/367

We are now adding the java version output to the metadata from the builds. Assuming this will now automatically appear in the API (CC @johnoliver ?), please provide the java -version output of each build on the download so users can track it back to a git branch and commit.

**Comment by johnoliver** [comment]
we are going to look at adding a link to the metadata file into the api on the Asset, so if the web page wants the version output it can pull that data via that link

**Comment by nickebbitt** [comment]
I've started looking at this

**Comment by M-Davies** [comment]
@nickebbitt Can this be closed?

**Comment by nickebbitt** [comment]
@karianna this now live so can be closed

**Comment by M-Davies** [comment]
See https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/235#issuecomment-687733912

**Comment by karianna** [comment]
Opened a website issue for this
