### ISSUE TITLE
Test suite currently takes ~40 mins to run

### ISSUE THREAD

**Issue by nickebbitt** [AdoptOpenJDK/openjdk-api-v3#238]
@johnoliver and I were discussing this yesterday and having started working with codebase it feels like it would be good to resolve the issue to improve the development feedback loop.

At present when each test class is executed there is an initial hit of between 1 and 2 minutes depending on the test. This acunulates to an overall time of ~40 mins to run the front-end test suite.

This is because the tests use the @QuarkusTest annotation which initialises the full app including the code that creates connections to Mongo. The default connect timeout for Mongo is 30000 milliseconds so every time a connection is attempted we get this hit.

We see these errors in the logs:

```
ERROR: Failed to read db
com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]
	at com.mongodb.internal.connection.BaseCluster.createTimeoutException(BaseCluster.java:403)
	at com.mongodb.internal.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:311)
	at com.mongodb.internal.connection.BaseCluster.access$800(BaseCluster.java:62)
	at com.mongodb.internal.connection.BaseCluster$WaitQueueHandler.run(BaseCluster.java:474)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

As a simple test for a fix I've modified the fallback localhost connection string that's used by the tests [here](https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt#L45) to this:

```
"mongodb://$host:$port?connectTimeoutMS=100"
```

The full test suite now runs in ~8 mins with the front-end tests reduced to ~5/6 mins:

```
[INFO] Reactor Summary for adoptopenjdk-api-v3 3.0.0-SNAPSHOT:
[INFO] 
[INFO] adoptopenjdk-api-v3 ................................ SUCCESS [  2.351 s]
[INFO] adoptopenjdk-api-v3-models ......................... SUCCESS [ 11.861 s]
[INFO] adoptopenjdk-api-v3-persistance .................... SUCCESS [  2.875 s]
[INFO] adoptopenjdk-api-v3-updater ........................ SUCCESS [02:41 min]
[INFO] adoptopenjdk-api-v3-frontend ....................... SUCCESS [05:29 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:28 min
[INFO] Finished at: 2020-07-16T08:30:57+01:00
[INFO] ------------------------------------------------------------------------
```

We could probably reduce this more but that's as far as I've gone for now, thought it was worth getting some feedback first.

I think as a quick win this could be a good change to improve the speed of the test run improving the feedback loop. 

Please let me know if you're happy for me to create a PR for this?

As the tests are using an in memory database controlled by the tests, longer term it may be worth thinking about how we either change the Mongo connection code to occur later in the application life-cycle so the database is already available. Or alternatively, and maybe preferably, change how we use Mongo in the tests so it's available before the Mongo client is created. Maybe something like test containers could help here, or even using docker-compose to wrap the test execution and spin up Mongo as a dependency.

---
Additional note: 

It's possible we'd want to apply a more aggressive timeout more generally than just the tests but that decision probably requires a bit more thought. In production waiting 30000ms for Mongo to notify that connection has failed might be too long, if we can fail faster then that might be a good thing. (I don't have much context yet on how this runs in prod).

**Comment by karianna** [comment]
@nickebbitt PR most welcome thank you!

**Comment by nickebbitt** [comment]
Cool. I'll take a look and consider whether it's worth exposing it as an environment variable similar to the Mongo config for the connection string, defaulting to existing behaviour of 30000ms.

The benefits for test execution time will be a nice win alone anyway.

**Comment by johnoliver** [comment]
yeah a system property that defaults to 30000, but is then overridden in tests sounds like the correct way to go

**Comment by nickebbitt** [comment]
I was slightly wrong with the above, it's actually the `serverSelectionTimeoutMS` that we need to set. When a connection attempt is made for a connection string that represents a Mongo server that's not yet running (e.g. with the tests prior to Fongo starting the embedded mongo instance) this will ensure it times out quickly rather than waiting 30000ms.

So it's literally this one line that causes the slow tests: https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/4567651a852311c3ac621d041b417a0390922dd1/adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt#L45

Changing it to this fixes the issue:

```
"mongodb://$host:$port/?serverSelectionTimeoutMS=100"
```

@johnoliver I may be making an assumption here but this looks like a pretty safe change as this "fallback" mongo connection string will not be used for production code. I was wondering if its how you run it locally in a stand-alone way? In any case this should also be fine assuming you local instance of mongo is running.

Also, following the test code through, and specifically what happens in in `BaseTest` to configure Fongo and its connection string via the `MONGO_DB` system property [here](https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt#L97-L105), I'm not sure there's anything to do for the tests as they override the initialisation in `MongoClient`. This code always runs after the initial connection attempts are made and Fongo is started at that point too so we see don't any server selection timeout issues.

---

Might just be chance/timing on my mac but that appears to be even quicker, shaved another minute off :)

```
[INFO] Reactor Summary for adoptopenjdk-api-v3 3.0.0-SNAPSHOT:
[INFO] 
[INFO] adoptopenjdk-api-v3 ................................ SUCCESS [  1.120 s]
[INFO] adoptopenjdk-api-v3-models ......................... SUCCESS [  9.532 s]
[INFO] adoptopenjdk-api-v3-persistance .................... SUCCESS [  2.146 s]
[INFO] adoptopenjdk-api-v3-updater ........................ SUCCESS [02:12 min]
[INFO] adoptopenjdk-api-v3-frontend ....................... SUCCESS [04:29 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:55 min
[INFO] Finished at: 2020-07-16T16:20:40+01:00
```
