### ISSUE TITLE
Fix pre version sort order

### ISSUE THREAD

**Issue by johnoliver** [AdoptOpenJDK/openjdk-api-v3#247]
Currently in the version sort order something comes after absent for the `pre` field. According to point 11 in https://semver.org/ absent should come after something.

**Comment by nickebbitt** [comment]
I think as a starting point adding some tests focused around [Release.kt](https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt) will be useful to demonstrate the existing behaviour.

This can then be used to evolve the sort order to meet the requirements of this issue.
