### ISSUE TITLE
Ability to request EA binaries the same as regular GA binaries without additional requests

### ISSUE THREAD

**Issue by bmuskalla** [AdoptOpenJDK/openjdk-api-v3#256]
I have the usecase that I want to download the latest available JDK for a specific Java version. Using the current APIs, I always need to do additional requests to properly feed the API:

Example: I want to download the latest JDK 15 for mac:
```
/v3/binary/latest/{feature_version}/{release_type}/{os}/{arch}/{image_type}/{jvm_impl}/{heap_size}/{vendor}
```
becomes:
```
/v3/binary/latest/15/{release_type}/mac/x64/jdk/hotspot/large/adoptopenjdk
```

This means I manually need to query `release_type` from some of the other APIs and those URLs are going to change the moment 15 GAs. Maybe a default that is automatically infered from the version number is enough.

Additionally, the `heap_size` option doesn't seem to be available in all combinations:
```
https://api.adoptopenjdk.net/v3/binary/latest/14/ga/mac/x64/jdk/hotspot/large/adoptopenjdk
```
The above query fails due to `large` heap size. This works:
```
https://api.adoptopenjdk.net/v3/binary/latest/14/ga/mac/x64/jdk/hotspot/normal/adoptopenjdk
```
Not sure if I can query this information somewhere or if it should properly downgrade if `large` is not available.

**Comment by johnoliver** [comment]
can look into this, but one note is that large heap is an openj9 feature

**Comment by johnoliver** [comment]
Actually I am not sure exactly what you are asking for here, `release_type` can be either `ea` or `ga`, when you say you need to query that from other APIs , I am not sure what you mean by that.

I think what you may be getting confused by, is that ea and ga refer to the difference is an ea is a nightly build which is simply a build of whatever the source code was at when the build happened, and ga however is a build of a proper release.  I.e `jdk11u-2020-07-27-06-54` would be an `ea`, `jdk-11.0.8+B10` would be a `ga`

**Comment by bmuskalla** [comment]
Thanks @johnoliver for the feedback on this. Good to know about the `large heap` option, might be worth putting that into the swagger docs or fallback to `normal` if this is not available.

Regarding the `GA` vs `EA`, yes, that confusion might be on my part. I think what I'm trying to accomplish is not really what the API is supposed to do. My use case is the following: A user gives me a Java major version, I want to download the corresponding JDK. I try to do the following which may simply require multiple calls:
* If it has a GA release, download the latest GA (e.g. `14` becomes `jdk-14.0.2+12`)
* If it has no GA release, download the latest EA (e.g. `15` becomes `jdk15-2020-07-27-05-19`)

And maybe I'm missing something but I'm struggling a bit with the current APIs to properly figure out this information efficiently. For example, to extract the above information manually, I could use the `/v3/info/release_names` but this ends up being multiple calls as well as the `/v3/info/release_names` API requires the `release_type` as well to decide the above request. Any thoughts how I could accomplish this with less API calls?

**Comment by johnoliver** [comment]
So as of right now you would need at least 2 calls, easiest way to do it would be a call to https://api.adoptopenjdk.net/v3/info/available_releases pretty much if the version the user wants is in the `available_releases` list or  less than or less than or equal to `most_recent_feature_release`, then there will be a ga available for that major version, if it is in the `most_recent_feature_version` then there will be EAs but no GAs.  But either way right now it would require at least 2 calls

**Comment by bmuskalla** [comment]
Thanks @johnoliver for clarification. Then I think my request is valid but out of scope for the current APIs.
