### ISSUE TITLE
Use Architecture Decisions Records (ADR) for the API

### ISSUE THREAD

**Issue by nickebbitt** [AdoptOpenJDK/openjdk-api-v3#270]
As a newcomer to the project it's difficult to understand the history of the API and how it's evolved to be where it is now.

Going forward it could be useful to use [ADRs](http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions) as a lightweight way to track key architectural decisions against the project. This will serve as both a historical record of how the project evolves, as well as a transparent and open mechanism for making decisions about future direction.

If seen to be a good idea, I'd recommend we store ADRs as markdown files in the codebase. This provides the benefits of keeping them close to the code, easy to edit and fully audited via Git history and through PRs an effective way to iterate on the decision and provide feedback.

A useful tool to help with this is: https://github.com/npryce/adr-tools

ADR Reference: http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions

**Comment by karianna** [comment]
I agree - annoyingly GitHub doesn't support mermaidjs yet which would make this easier.
