### ISSUE TITLE
API blocks User-Agent "Java/1.8.0_201"

### ISSUE THREAD

**Issue by dracorp** [AdoptOpenJDK/openjdk-api-v3#273]
I use [JSON Table Macro](https://bobswift.atlassian.net/wiki/spaces/TBL/pages/68649140/JSON+Table+Macro) for Confluence in order to obtain latest versions of openjdk. Unfortunately this kind request is blocked. The problem is with User Agent:
```
curl -s  https://api.adoptopenjdk.net/v3/info/available_releases -A "Java/1.8.0_201"
error code: 1010
```
but 
```
$ curl -s  https://api.adoptopenjdk.net/v3/info/available_releases -A "Java/1"

{
    "available_lts_releases": [
        8,
        11
    ],
    "available_releases": [
        8,
        9,
        10,
        11,
        12,
        13,
        14
    ],
    "most_recent_feature_release": 14,
    "most_recent_feature_version": 15,
    "most_recent_lts": 11,
    "tip_version": 16
}
``` 
is not blocked.
I cannot change User-Agent. Can you unblock this kind UA?

**Comment by nickebbitt** [comment]
for info, I wrote a simple test in [AvailableReleasesPathTest](https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AvailableReleasesPathTest.kt) for this that passes at the JVM level so could this possibly be failing at the edge, maybe Cloudflare is dropping it?

```
    @Test
    fun `user agents`() {
        RestAssured.given()
            .header("User-Agent", "Java/1.8.0_201")
            .`when`()
            .get("/v3/info/available_releases")
            .then()
            .statusCode(200)
    }
```

**Comment by johnoliver** [comment]
I can confirm it is definitely the app and not cloudflare, not sure what is causing it yet

**Comment by johnoliver** [comment]
Actually, forget that, the app does service these requests correctly, the problem is somewhere upstream

**Comment by nickebbitt** [comment]
Interesting, it's very possible my test is wrong but it's if not then then it's a bit worrying as it indicates our tests aren't exercising the the front-end Quarkus app as thoroughly as they should be.

**Comment by nickebbitt** [comment]
ah just spotted your update 👍

**Comment by johnoliver** [comment]
looking at https://community.cloudflare.com/t/getting-banned-from-my-own-site-error-1010/149617 certainly seems like this is in the cloudflare are

**Comment by gdams** [comment]
I have disabled `Browser Integrity Check` in Cloudflare.

Confirmed to be fixed:

```
➜  ~ curl -s  https://api.adoptopenjdk.net/v3/info/available_releases -A "Java/1.8.0_201"

{
    "available_lts_releases": [
        8,
        11
    ],
    "available_releases": [
        8,
        9,
        10,
        11,
        12,
        13,
        14
    ],
    "most_recent_feature_release": 14,
    "most_recent_feature_version": 15,
    "most_recent_lts": 11,
    "tip_version": 16
}%       
```
