### ISSUE TITLE
Load testing the API

### ISSUE THREAD

**Issue by nickebbitt** [AdoptOpenJDK/openjdk-api-v3#281]
During a discussion with @johnoliver we talked about how it would be good to add a load testing capability to the project. The goal of this being to understand the current throughput that the API can handle.

Some initial thoughts are:
* it would be nice if the tests were driven from the [OpenAPI docs](https://api.adoptopenjdk.net/openapi)
* possibly use Gatling or JMeter

**Comment by karianna** [comment]
Swagger sells testing and load testing.  Other load testing services may be able to generate a load based on a swagger definition.

**Comment by karianna** [comment]
https://github.com/adoptium/api.adoptium.net/issues/212
