### ISSUE TITLE
Improve how we manage test asset data

### ISSUE THREAD

**Issue by nickebbitt** [AdoptOpenJDK/openjdk-api-v3#282]
We currently have a set of test data that is used for various tests:
- test data: https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/adoptopenjdk-api-v3-updater/src/test/resources/example-data.json.gz
- usage: https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt#L88 

This data is static and was generated at a point in time. It is rarely updated.

During a discussion with @johnoliver we talked about the need to think about how ensure the tests / test data stays current and up-to-date.

**Comment by nickebbitt** [comment]
@johnoliver does #290 resolve some or all of the concerns covered by this issue?

**Comment by johnoliver** [comment]
yes that pr should resolve this

**Comment by nickebbitt** [comment]
@johnoliver I think this one can be closed now?

**Comment by johnoliver** [comment]
yep should be
