### ISSUE TITLE
Implement changes for ADR 2: Branching & Release Strategy

### ISSUE THREAD

**Issue by nickebbitt** [AdoptOpenJDK/openjdk-api-v3#284]
Following acceptance of the [ADR](https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/docs/adr/0002-branching-and-release-strategy.md) we now need to implement the decision.

This requires us to:

- [x] update CONTRIBUTING.md to instruct contributors to raise PRs against `master` and describe the production release process.
- [x] create the new `production` branch that will be deployed to the production environment - **NOTE:** branch protection should be enabled
- [x] modify OpenShift deployment process to point Staging environment at `master` 
- [x] modify OpenShift deployment process to point Production environment at the new `production` branch
- [x] once all above complete, delete the `staging` branch

**Comment by nickebbitt** [comment]
@johnoliver have I missed anything from what's required to implement this?

**Comment by johnoliver** [comment]
That all sounds good to me. Think only thing would be adding branch protection in github to the `production` (fyi my vote is for `production`) branch. 

Something else we might consider is actually bumping versions in the pom during releases. So maybe we want some github actions to merge into `production` and bump versions. But those can be figured out later

**Comment by nickebbitt** [comment]
Thanks, I'll edit the above with that feedback. I like the idea of versions and having a GitHub Action do the work, good shout 👍

**Comment by nickebbitt** [comment]
Now the Java 15 released is this a good time to work through the changes for this ADR? 

A pre-requisite would probably to get @johnoliver's PR #290 merged and then take that as the clean cut-over point.

I can pick the changes to CONTRIBUTING.md but will need someone else to cover creating the new `production` branch and changes to the OpenShift deployment.

**Comment by nickebbitt** [comment]
@johnoliver do you want to do the honours of deleting the staging branch? then we can close this issue off.

https://github.com/AdoptOpenJDK/openjdk-api-v3/tree/staging
