### ISSUE TITLE
Add Code of Conduct for contributors

### ISSUE THREAD

**Issue by nickebbitt** [AdoptOpenJDK/openjdk-api-v3#291]
**🆕🐥🐶 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**

At present we don't have a clear code of conduct (CoC) for this project which would be useful for new contributors, and particularly for things like [Hacktoberfest](https://hacktoberfest.digitalocean.com).

We should add a CoC, the [IcedTea-Web project](https://github.com/AdoptOpenJDK/IcedTea-Web) has already set a precedent for this:
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/CODE_OF_CONDUCTION.md

**📋 Step by Step**

To solve this issue and contribute a fix to AdoptOpenJDK API you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master of the AdoptOpenJDK API project.
- [ ]  Thanks, thanks, thanks for being part as an open source contributor for AdoptOpenJDK API ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by sachinp97** [comment]
hi, can I claim this issue?

**Comment by nickebbitt** [comment]
hey @sachinp97 - when this originally came up there was some discussion around the CoC being defined at the AdoptOpenJDK level and then applied across all projects i.e. we would probably link to it elsewhere

Since then though, we've moved to Eclipse and there's the rebrand to Adoptium so things have changed a fair bit.

I appreciate the the time you've put in to create the PR for this but I think it's worth getting @karianna's input before proceeding further.

**Comment by sachinp97** [comment]
Sure thanks @nickebbitt!
@karianna , please let me know if there are any corrections or samples that I need to use for this pull request.

**Comment by karianna** [comment]
I think a CODE_OF_CONDUCT.md file can simply refer to https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php
