### ISSUE TITLE
Add update POST route

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-api-v3#304]
I don't like how long it takes for the V3 API to pick up releases. I've previously thought about adding a POST route that allows us to specify a particular release for the API to immediately crawl. We could add a token to the route and automate the request as part of the release pipeline. A simple POST route would allow us to very quickly tell the API to crawl small amounts of data. It would also mean that we could probably dial back the 15 min check to 30 mins or an hour

**Comment by nickebbitt** [comment]
Happy to pick this one up next. I'll do a bit of analysis and come back with a high-level proposal before getting too deep into any implementation.

One question to start, do we have a preferred authentication mechanism either used already with the API (not seen one) or used with other Adopt services?

**Comment by nickebbitt** [comment]
@gdams the awkward thing about this idea is that the `updater` module handles the task of reading release info from GitHub and writing to Mongo, which then gets served up by the `frontend`. The `updater` is headless and is essentially a daemon process that runs the scheduled tasks to" full update" every 24 hours for a full refresh and an "incremental update" every 3 minutes.

I'll do some more digging to gain a better understanding of the `updater` to see if there's something we can do there or not.

One option that comes to mind would be to allow the `frontend` to write some simple state to the DB that indicates to the `updater` next time it runs that it should also do some extra work however this feels like it moves away from the current architecture a little with clear read/write responsibilities so it';s definitely worth more discussion.

@johnoliver do you have any thoughts on this?

**Comment by gdams** [comment]
@johnoliver are you able to comment on this? It's becoming more and more of an issue so would be good to get this improved.

**Comment by karianna** [comment]
John recommends using jgroups to use as a comms channel to relay the request from the front end to the back end

**Comment by karianna** [comment]
Fixed.
