### ISSUE TITLE
Circumvent long updater times

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-api-v3#309]
**Is your feature request related to a problem? Please describe.**
When replicating the API locally, the updater tool will take a long time to complete and can often leave you twiddling your thumbs while you wait for the database to populate.

**Describe the solution you'd like**
A quicker or easier way of checking new changes you make the API without having to build the whole thing again. 
- @nickebbitt has [suggested having a method of building the API in a lightweight mode](https://adoptopenjdk.slack.com/archives/CFUJV9XV0/p1605263936091200?thread_ts=1605216200.084500&cid=CFUJV9XV0) using only one version and variant which could be one way of achieving a shorter development time.
- Or modify the Mongo service the docker-compose specifies to persist it’s data via a volume mount each time the updater completes. This would save having to build and rebuild the same data over and over again but still allow new changes to take effect

**Describe alternatives you've considered**
A Jenkins job that builds the artifacts, runs the updater tool and exposes both of these things that people can then download and plug in to their own mongodb instances. This would mean that we would always have artifacts available to new contributors and they can get started straight away. I have no idea how feasible this would be under Mongo restrictions however.

**Comment by johnoliver** [comment]
the api tests now generate their own test data, so this should not be an issue

**Comment by nickebbitt** [comment]
I think what @M-Davies is after is a way of actually running the API locally without it having to run a full update and populate the Mongo database, rather than from an automated test perspective.

The idea we discussed briefly was a mechanism (possibly an environment variable) that can be used to filter the releases that the API loads, for example, so it only loads a specific set of semvers.

**Comment by karianna** [comment]
Related to #304 ?

**Comment by karianna** [comment]
There are now test data for unit tests and staging has the faster updater for the production use case.

**Comment by M-Davies** [comment]
> There are now test data for unit tests and staging has the faster updater for the production use case.

Unit tests can only go so far imo. Yes they are useful at identifying whether a solution has worked BEHIND the scenes but do nothing to prove that the data appears in the API frontend as you would expect it to. Regarding staging, are you referring to the staging branch or master branch [which represents "the live staging environment"](https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/CONTRIBUTING.md#source-code-management--branching)?

If it is the former, then that does not really fit the bill either as the staging branch has heavily diverged from both the master and prod branches, likely meaning that any changes you wish to make against the master branch cannot be tested in the staging branch as conflicts would occur and the resulting view would be different. With regards to the latter, although the updater time maybe quicker, it is still in excess of 18hrs or more (I know as I am currently running one for #365 🙂). I don't think we should be disregarding the possibility of allowing builds to filter which test release data is picked up or what data is retained after those builds to save subsequent build time (as mentioned above https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/309#issuecomment-738156072)

**Comment by karianna** [comment]
Passing onto @johnoliver for comment

**Comment by karianna** [comment]
Updater times are now within acceptable bounds.
