### ISSUE TITLE
swagger-ui doesnt seem to work

### ISSUE THREAD

**Issue by gmcdonald** [AdoptOpenJDK/openjdk-api-v3#312]
Hi, the swagger-ui provides 'Try It Out' button for testing of the API, it also provides built in options to choose from.
One would expect all of these to work, but from my testing, none of them worked. In addition, the example output provides a curl command to copy and paste to a command line, which also does not work as provided.

1. Go to https://api.adoptopenjdk.net/swagger-ui/
2. Click on the /v3/binary/version area to expand that section.
3. Click on 'Try It Out'
4. Accept the default options provided
5. Scroll down the the end of the expanded section and click on 'Execute'

Following the above, I'd expect to see a 200 response, success, possibly including a 302 redirect.
what happens is that we ge file not found, a 307, 400 and 404 messages. Seems that swagger itself is 
failing to find the resources requested at the urls it provides.

In addition, the swagger ui provides a curl command, presumably to copy and paste to a local command 
line  for testing/use. That too fails with a 400 bad request.

Pasting the https provided output into a browser does succeed. Presumably the browser follows redirects 
automatically. 

Screenshot of failed example using defaults as provided.
![image](https://user-images.githubusercontent.com/287517/99247127-cc73fb80-2806-11eb-82e4-9fb499dd6ddf.png)

Environment : 

tested on MacOS Catalina, using Google Chrome version 86
tested with curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2

**Additional context**

With help on the adoptoopenjdk slack api channel, seems adding -L option to curl and all works fine. 
Perhaps the swagger-ui needs to employ the same fix?

**Comment by nickebbitt** [comment]
Possibly related to https://github.com/swagger-api/swagger-ui/issues/3403

I think a first port of call will be to do some version bumps and make sure we're up-to-date as that issues mentions https://github.com/swagger-api/swagger-ui/pull/4295 which will at least improve the message received on the UI.

I've been trying to track down the version of Swagger UI that Quarkus pulls in but it's not been as easy as it sounds.

**Comment by nickebbitt** [comment]
It's definitely CORS related as we see the following error in Chrome's Developer Tools console log
```
Access to fetch at 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz' (redirected from 'https://api.adoptopenjdk.net/v3/binary/version/jdk-11.0.6%2B10/linux/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk') from origin 'https://api.adoptopenjdk.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by johnoliver** [comment]
I think this is related to the fact that ultimately the end result of that redirect is a file download, that I am not sure how the UI reasonably would represent this.
