### ISSUE TITLE
EA/GA filter is not working as expected

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/openjdk-api-v3#318]
**Describe the bug**
For v3/info/release_versions the "release_type" filter doesn't work

>release_typestring(query) | Type of release. Either a release version, known as General Availability(ga) or an Early Access(ea)
Available values : ga, ea
Default value : ga

**To Reproduce**
1. Filter on GA give me 3 EA release : 
curl -X GET "https://api.adoptopenjdk.net/v3/info/release_versions?page=0&page_size=10&release_type=ga&sort_method=DEFAULT&sort_order=DESC&vendor=adoptopenjdk&version=%5B11%2C11.1%29" -H "accept: application/json" |grep ea
11.0.7-ea+10.1
11.0.8-ea+10
11.0.9-ea+11

2. and filtering on EA give me no EA but only what I think is nightly

curl -s -X GET "https://api.adoptopenjdk.net/v3/info/release_versions?page=0&page_size=10&release_type=ea&sort_method=DEFAULT&sort_order=DESC&vendor=adoptopenjdk&version=%5B11%2C11.1%29" -H "accept: application/json" |grep ea

>A clear and concise description of what you expected to happen.

I expect that the ga filter doesn't return EA build
I expect ea filter return the 3 build seen in ga
Maybe we must add a filter for nightly .. or rename ea with nightly and ga with gaAndEA

**Comment by karianna** [comment]
This is because we've conflated nightlies vs. EA vs. GA

Unlikely to fix this at adoptopenjdk.net may look to fix at adoptium.net

**Comment by karianna** [comment]
https://github.com/adoptium/api.adoptium.net/issues/213
