### ISSUE TITLE
jdk8 openj9 nightly builds haven't been published nightly 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-api-v3#337]
Query jdk8 openj9 nightly sdk will only get builds of Dec 8th. 

https://api.adoptopenjdk.net/v3/binary/latest/8/ea/mac/x64/jdk/openj9/normal/adoptopenjdk

https://adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9

```
10:39:20  openjdk version "1.8.0_282"
10:39:20  OpenJDK Runtime Environment (build 1.8.0_282-202012080915-b04)
10:39:20  Eclipse OpenJ9 VM (build openj9-0.24.0-m1, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20201208_800 (JIT enabled, AOT enabled)
10:39:20  OpenJ9   - c757b5115
10:39:20  OMR      - 5080dab1e 
10:39:20  JCL      - 9910cb2350 based on jdk8u282-b04)
```

Nightly build looks good https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9/. Looks like there are some publishing issue?

**Comment by aahlenst** [comment]
They are on https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u-2020-12-24-13-12, so publication seems to be fine. Builds from today appear on the website, just *after* the EAs from the 8th of December. So probably a sorting issue again.

**Comment by sxa** [comment]
@johnoliver is working on a fix for this at the moment
