### ISSUE TITLE
Improve Code Generator interoperability by not including "example"-values in allOf-container for ZonedDateTime

### ISSUE THREAD

**Issue by AliveDevil** [AdoptOpenJDK/openjdk-api-v3#350]
**Describe the bug**
Using the AdoptOpenJDK OpenAPI endpoint to generate client code results in invalid code generated.

This effects
* Binary#updatedAt
* Release#timestamp
* Release#updatedAt

**To Reproduce**
1. Create .NET 5 project
    - Sample project is attached ([AdoptOpenJDKTest.zip](https://github.com/AdoptOpenJDK/openjdk-api-v3/files/5887995/AdoptOpenJDKTest.zip))
2. try to compile the code
    - The sample project already contains the OpenAPI definition from time of creation
3. Errors out

IMO type restrictions should not include an example-parameter, which confuses many code-generators out there:
```
"Binary" : {
  "type" : "object",
  "properties" : {
    "updated_at" : {
      "allOf" : [ {
        "$ref" : "#/components/schemas/ZonedDateTime"
      }, {
        "example" : "2018-03-15T12:13:07Z"
      } ]
    }
  }
}
```

**Expected behavior**
As ZonedDateTime is a Java internal type there is no way of setting the Example-property for this type. Though it can be achieved by using following structure on the OpenAPI definition:
```
"Binary" : {
  "type" : "object",
  "properties" : {
    "updated_at": {
      "type": {
        "$ref": "#/components/schemas/ZonedDateTime"
      },
      "example": "2018-03-15T12:12:35Z"
    }
  }
}
```
Explicitely add the type-parameter, and add the example onto the property, instead of setting the schema allOf-type.
As I'm not used to the OpenAPI on Java it looks like `@ExampleObject(value="YYYY-MM-DDTHH-mm-SSZ")` might be enough, though the OpenAPI renderer might have to intervene here and add the `type`-property.

**Screenshots**
This looks exactly the same, but works much better for code generators as there are not two competing types (DateTime and String) and the example is applied just like before.
![image](https://user-images.githubusercontent.com/734738/106151623-d4dca100-617c-11eb-8be3-b566f871459d.png)

**Device (please complete the following information):**
- C#, NSwag code generation via .NET 5 OpenAPIReference

**Additional context**
[NSwag Tracking-Issue](https://github.com/RicoSuter/NSwag/issues/3276)

Edit: Attached sample project.

**Comment by karianna** [comment]
@johnoliver I think I saw you remove example in a recent PR is that right?

**Comment by johnoliver** [comment]
Put in a PR to wrap our own DateTime type rather than using a Java type, @AliveDevil hopefully will work for you

**Comment by johnoliver** [comment]
@AliveDevil check out https://staging-api.adoptopenjdk.net/openapi and see if it works for you

**Comment by AliveDevil** [comment]
Hi, thanks for looking into this. Now the code gen correctly identifies the "updated_at" as String … though consuming projects would need to convert that into a DateTime while running themselves.
```
[Newtonsoft.Json.JsonProperty("updated_at", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
public string Updated_at { get; set; }
```
So … having to deal with a String is far better than trying to get around the DateTimeOffset-subclassing mess. Thanks!
