### ISSUE TITLE
Provide informations which major versions are currently supported

### ISSUE THREAD

**Issue by P1tt187** [AdoptOpenJDK/openjdk-api-v3#357]
**Is your feature request related to a problem? Please describe.**
I'm providing an internal Docker container in my employer. The main goal is to provide all currently supported JDK versions.
At this moment I need to hard code the versions in the container. So my Team is forced to change the Container with every new released version and review the changes.

**Describe the solution you'd like**
An api Call like the following:
Request: `/v3/info/supported_versions`
Answer: `{ "versions":[8,11,15] }`

**Comment by nickebbitt** [comment]
Hi, how do you interpret currently supported at your organisation?

We already provide details of Long-Term Support (LTS) versions via the API which are `8` and `11` e.g.

```
$ curl -X GET "https://api.adoptopenjdk.net/v3/info/available_releases" -H "accept: application/json"                                             17:02:49

{
    "available_lts_releases": [
        8,
        11
    ],
    "available_releases": [
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15
    ],
    "most_recent_feature_release": 15,
    "most_recent_feature_version": 17,
    "most_recent_lts": 11,
    "tip_version": 17
}%
```

This also provides details of the `most_recent_feature_release` which is `15` so maybe the combination of this can provide what you need?

I may be wrong but in your example you specify version `14` however my understanding is that when `15` was released support for that ended, and the same will apply to `15` when `16` is released.

**Comment by P1tt187** [comment]
Hi thanks for the quick reply. Your're right, the `14` is not correct, sry for that.
For me all major versions are supported, or maintained, which will get new releases.

Or more simply explained:
When looking at the table featured on this page
https://adoptopenjdk.net/support.html
All versions which are currently available and where the column **Next Release** is not empty.

Thanks for the example from the api, I will try that out.

**Comment by P1tt187** [comment]
The example api call provides the information i've searched for.
Here is a snipplet that works for me
```sh
WHAT_JDK_IS_AVAILABLE=$( curl -X GET "https://api.adoptopenjdk.net/v3/info/available_releases" -H "accept: application/json" )
LTS_RELEASES=$(echo "$WHAT_JDK_IS_AVAILABLE" | python2 -c "import sys, json; L=json.load(sys.stdin)['available_lts_releases']; print(' '.join(map(str, L)))")
MOST_RECENT_FEATURED_RELEASE=$(echo "$WHAT_JDK_IS_AVAILABLE" | python2 -c "import sys, json; print(json.load(sys.stdin)['most_recent_feature_release'])")
MOST_RECENT_LTS_RELEASE=$(echo "$WHAT_JDK_IS_AVAILABLE" | python2 -c "import sys, json; print(json.load(sys.stdin)['most_recent_lts'])")
ADOPTOPENJDK_VERSIONS="$LTS_RELEASES $MOST_RECENT_FEATURED_RELEASE"
defaultJdkName="adoptopenjdk-${MOST_RECENT_LTS_RELEASE}-hotspot-amd64"
```

Thank you for your advise. 👍
