### ISSUE TITLE
Review p Java 13 and 15

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-api-v3#360]
**Describe the bug**
We prematurely marked Java 13 and 15 as obsoleted in the API

**Expected behavior**
13 is still maintained by Azul (even if ew don;t ship them in the API today, we may tomorrow) and 15 is not out of support yet (2 weeks to go).

**Comment by nickebbitt** [comment]
I'll push a fix for this shortly

**Comment by aahlenst** [comment]
@karianna Is there a discussion/policy around that (= marking 13 as non-obsolete)? Isn't MTS limited to x64? And why does our API inform about things we don't ship? From a user's perspective, it's weird to see 13 as active while I won't get updates.

**Comment by karianna** [comment]
> @karianna Is there a discussion/policy around that (= marking 13 as non-obsolete)? Isn't MTS limited to x64? And why does our API inform about things we don't ship? From a user's perspective, it's weird to see 13 as active while I won't get updates.

We'll discuss again at the TSC - but I think we made a mistake previously of shutting out 13 from the API as _other_ vendors do provide updated 13 binaries since the upstream source is still being worked on.  For example, we should be making Zulu 13 builds through the API (but not Temurin builds)

**Comment by aahlenst** [comment]
> We'll discuss again at the TSC - but I think we made a mistake previously of shutting out 13 from the API as other vendors do provide updated 13 binaries since the upstream source is still being worked on. For example, we should be making Zulu 13 builds through the API (but not Temurin builds)

Does the API expose enough information to support such an use case? AFAIK not. We basically need a list of supported versions per vendor. Currently, Azul supports 7, 8, 11, 13, 15, while we support 8, 11, 15. So if the API said 13 is supported by everyone, people with AdoptOpenJDK 13 will wait for updates that never come.

**Comment by karianna** [comment]
Yeah, we'll need to split that out - not sure if that can be done in a way that doesn't break backwards compat
