### ISSUE TITLE
Querying for release names of specific version results in Internal Server Error

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-api-v3#362]
**Describe the bug**

When asking the API for release names of a specific version, it returns an error:

```
$ curl -X GET "https://api.adoptopenjdk.net/v3/info/release_names?page=0&page_size=10&sort_method=DEFAULT&sort_order=DESC&vendor=adoptopenjdk&version=17" -H  "accept: application/json"
{"details":"Error id 59ab7073-8692-453e-92cf-157865ad9a8d-38","stack":""}%  
```

The URL was created with Swagger UI. 17 is a valid version name, so is 16, which fails, too:

```
$ curl -X GET "https://api.adoptopenjdk.net/v3/info/release_names?page=0&page_size=10&sort_method=DEFAULT&sort_order=DESC&vendor=adoptopenjdk&version=16" -H  "accept: application/json"
{"details":"Error id 38198dff-8c2b-4432-b3d5-0ce40054d128-13","stack":""}% 
```

**To Reproduce**
Run

```
curl -X GET "https://api.adoptopenjdk.net/v3/info/release_names?page=0&page_size=10&sort_method=DEFAULT&sort_order=DESC&vendor=adoptopenjdk&version=17" -H  "accept: application/json"
```

**Expected behavior**
JSON returned with the available releases.

**Device (please complete the following information):**

```
curl --version
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by johnoliver** [comment]
Currently the release_names version parameter takes a version range or exact version i.e:

https://staging-api.adoptopenjdk.net/v3/info/release_names?version=[15,16]

17 is neither an exact version or a range, I could see an argument for making major versions an equivalent of a range, i.e `17=[17,18)` I will need to check if it will break anything but I dont think so

**Comment by nickebbitt** [comment]
is it straightforward to return 400 Bad Request, at least for now? I could take a little look at this bit to improve the user experience

**Comment by johnoliver** [comment]
Yeah it is poor behaviour right now that we throw a server error rather than an informative 400 error

**Comment by karianna** [comment]
Fixed
