### ISSUE TITLE
Consider increasing max page_size > 20

### ISSUE THREAD

**Issue by maxim-lobanov** [AdoptOpenJDK/openjdk-api-v3#370]
**Is your feature request related to a problem? Please describe.**
We use Adopt OpenJDK API V3 to retrieve the list of all available binaries for specific platform / architecture / release type and other parameters. We use endpoint `https://api.adoptopenjdk.net/v3/assets/version` to the get the list of available versions and stuck around max `page_size=20` limit.

_A bit context why we need to retrieve all versions: we select specific binary based on customer's input (customer specifies SemVer input that couldn't be easily converted to Gradle Version)._ so we have to get all version firstly and then filter them.

Everything works great for `ga` versions because there is small number of those versions (~50) but for `ea` - there is a huge number of versions (~2.5k even if we include all filters) and it could be very painful to paginate them via max page_size = 20

(JFYI, Zulu API returns ~2k versions via single request)

**Describe the solution you'd like**
Increase `page_size` limitation to 100 / 500 to simplify pagination for cases where we need to retrieve all versions.
I don't think that it should affect server performance much but it would significantly simplify provided use-case. Considering the fact that you provide such huge number of versions, page_size=20 looks very small.

**Describe alternatives you've considered**
If you think that `/v3/assets/version/{version}` returns too much information, may be you could consider increasing page size limit for `/v3/info/release_versions` that returns versions only?

**Additional context**
cc: @gdams

**Comment by gdams** [comment]
@maxim-lobanov you can increase the page size with the `page_size` parameter? Does that not solve your issue?

Check out https://api.adoptopenjdk.net/swagger-ui/#/Assets/get_v3_assets_version__version_ for more info

**Comment by maxim-lobanov** [comment]
@gdams , Yes, but it is limited by `20` afaik. If you set `page_size=30`, API will return 20 elements.
I guess it comes from https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/2f40f2db9258909e461543062502d1eacede2502/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt#L8

**Comment by johnoliver** [comment]
@maxim-lobanov can take a look at the performance impact, think the main issue as you stated would be the amount of network traffic, currently we are looking at about 10kb per release we return, so 100/500 would be about 1mb/5mb per page, which is quite a lot for an api to return in a single page. However for the release_versions end point it would be far less, we could probably return 100's from there without a problem.

**Comment by maxim-lobanov** [comment]
Sorry for confusing, I was wrong - `/v3/info/release_versions` endpoint doesn't work for our use-case because it doesn't allow to filter versions by platform / architecture / package type and I assume that not all versions have binaries for every platform (we need to retrieve the list of versions that have available binaries for specific arch / os.

As for the `v3/assets/version`, I agree with your point. I have checked the release size from my side but it was ~2 kb per version for me because we filter by os / arch and every release contained the single binary. Returning 5MB from the single request looks unacceptable but may be increasing limit from 20 to 50/100 might be acceptable.

Please let me know if you see any other options to achieve our goal. 
P.S. May be there is some huge static json file that contains all versions and can be downloaded and filtered locally 😄 instead of pagination.

**Comment by johnoliver** [comment]
I think it is reasonable we bring all the filter parameters used on other endpoints onto the `release_names` and `release_versions` endpoints. I presume that would work for you?

**Comment by maxim-lobanov** [comment]
Hello @johnoliver , did you have a chance to take a look at this issue?

**Comment by johnoliver** [comment]
I did, #385 I believe has what we would expect functionality wise, I have not got around to implementing the extended testing of the new functionality though

**Comment by maxim-lobanov** [comment]
Thank you for sharing latest status! Looks good to me!

**Comment by johnoliver** [comment]
@maxim-lobanov code is up on staging now, can you check:
- https://staging-api.adoptopenjdk.net/q/swagger-ui/#/Release%20Info/getReleaseNames
- https://staging-api.adoptopenjdk.net/q/swagger-ui/#/Release%20Info/getReleaseVersions
works for you? Note that if you try it in swagger you will need to change the target server in the drop down menu at the top of the page.

**Comment by dmitry-shibanov** [comment]
Hello @johnoliver. Thank you for help and sorry for long response. It looks like everything works as expected. Could you please tell us when changes will be deployed to the `PROD` ?

**Comment by johnoliver** [comment]
its merged, thanks
