### ISSUE TITLE
OutOfMemoryError on docker-compose build frontend

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-api-v3#377]
**Describe the bug**
I have been trying to replicate the Adopt API Locally using the instructions in `contributing.md` and `structure.md` and have hit this error both in the artifact generator (`mvnw clean install`) in a very similar way to https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/298 

Furthermore, this also occurs when building inside of a docker container with `docker-compose build`)

**To Reproduce**
1. Clone this repo.
2. Install Java 11, my version is 
```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```
3. Created a GitHub PAC Token with the public repo permission enabled.
4. Followed the recommended guide to install mongo in `contributing.md`. I also did `brew install maven` at this point (even though I'm fairly sure it's not needed)
5. `./mvnw clean install`
6. See error in **Screenshots**

**Expected behavior**
Maven build passes, allowing me to run the updater tool that has been created by maven

**Screenshots**
```
#11 182.3 Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-compress/1.20/commons-compress-1.20.jar
Progress (5): 2.1/2.8 MB | 1.6/7.9 MB | 1.2/1.5 MB | 1.1/1.2 MB | 573/632 kB
#11 183.1 [output clipped, log limit 1MiB reached]
#11 300.7 Mar 20, 2021 11:57:49 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
#11 300.7 WARNING: TestEngine with ID 'junit-jupiter' failed to execute tests
#11 300.7 java.lang.OutOfMemoryError: Java heap space
#11 300.7 	at java.base/java.util.Arrays.copyOfRange(Arrays.java:4030)
#11 300.7 	at java.base/java.lang.StringLatin1.newString(StringLatin1.java:715)
#11 300.7 	at java.base/java.lang.String.substring(String.java:1879)
#11 300.7 	at org.json.JSONTokener.nextString(JSONTokener.java:210)
#11 300.7 	at org.json.JSONTokener.nextValue(JSONTokener.java:107)
#11 300.7 	at org.json.JSONTokener.readObject(JSONTokener.java:362)
#11 300.7 	at org.json.JSONTokener.nextValue(JSONTokener.java:100)
#11 300.7 	at org.json.JSONTokener.readArray(JSONTokener.java:430)
#11 300.7 	at org.json.JSONTokener.nextValue(JSONTokener.java:103)
#11 300.7 	at org.json.JSONTokener.readObject(JSONTokener.java:385)
#11 300.7 	at org.json.JSONTokener.nextValue(JSONTokener.java:100)
#11 300.7 	at org.json.JSONTokener.readObject(JSONTokener.java:385)
#11 300.7 	at org.json.JSONTokener.nextValue(JSONTokener.java:100)
#11 300.7 	at org.json.JSONTokener.readObject(JSONTokener.java:385)
#11 300.7 	at org.json.JSONTokener.nextValue(JSONTokener.java:100)
#11 300.7 	at org.json.JSONTokener.readObject(JSONTokener.java:385)
#11 300.7 	at org.json.JSONTokener.nextValue(JSONTokener.java:100)
#11 300.7 	at org.json.JSONTokener.readObject(JSONTokener.java:385)
#11 300.7 	at org.json.JSONTokener.nextValue(JSONTokener.java:100)
#11 300.7 	at org.json.JSONTokener.readObject(JSONTokener.java:385)
#11 300.7 	at org.json.JSONTokener.nextValue(JSONTokener.java:100)
#11 300.7 	at org.json.JSONObject.<init>(JSONObject.java:155)
#11 300.7 	at org.json.JSONObject.<init>(JSONObject.java:172)
#11 300.7 	at org.skyscreamer.jsonassert.JSONParser.parseJSON(JSONParser.java:43)
#11 300.7 	at org.skyscreamer.jsonassert.JSONCompare.compareJSON(JSONCompare.java:49)
#11 300.7 	at org.skyscreamer.jsonassert.JSONCompare.compareJSON(JSONCompare.java:125)
#11 300.7 	at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:415)
#11 300.7 	at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:394)
#11 300.7 	at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:336)
#11 300.7 	at net.adoptopenjdk.api.APIDataStoreTest$dataIsStoredToDbCorrectly$1.invokeSuspend(APIDataStoreTest.kt:38)
#11 300.7 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
#11 300.7 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
#11 300.7 
------
executor failed running [/bin/sh -c ./mvnw package]: exit code: 1
ERROR: Service 'frontend' failed to build
```

**Device (please complete the following information):**
- OS: MacOS Big Sur, Version 11.2.1
- Browser: Chrome 89.0.4389.90 (Official Build) (x86_64)
- Version: I assume this means the repo? In which case, it's the same version as the current master branch (and is being executed on the master branch)

**Additional context**
I did have a quick google for memory issues and found [this thread](https://stackoverflow.com/questions/1565388/increase-heap-size-in-java) to increase heap sizes on the fly. However, it would be good to have a solution that does not involve hard coding a `-xmx` value in

**Comment by johnoliver** [comment]
How much memory does the machine you are building on have? Surprised as we run ok on github actions, I cant see how much memory those nodes have but I wouldn't expect a lot.

**Comment by M-Davies** [comment]
8GB 2133MHz DDR3. The problem might have gone away or been due to the machine interrupting the run when it went to sleep the other day, I have re-run `docker-compose build` to see if it occurs again. I will reopen this issue if it does
