### ISSUE TITLE
Adopt OpenJDK binaries are not available for Windows x86 arch

### ISSUE THREAD

**Issue by maxim-lobanov** [AdoptOpenJDK/openjdk-api-v3#389]
**Describe the bug**
If you open Adopt OpenJDK site, you will see that binaries for Windows x86 are available.
But if do API request, it will return nothing for Windows x86 architecture.
Looks like in API, I should specify architecture as x32.
Not sure if it is actually API bug or incorrect documentation on official Adopt OpenJDK site but it is confusing for customers.

**Expected behavior**
- API should return the correct list for Windows x86 architecture (the same list like for x32 probably)
or
- Adopt OpenJDK should be updated to show x32 arch.

I am not sure what is the better way but in our understanding, API and description should be consistent.

**Screenshots**
![image](https://user-images.githubusercontent.com/16715858/114750230-6d39f900-9d5c-11eb-8c31-c6fc74264c9a.png)
![Screen Shot 2021-04-14 at 8 03 51 PM](https://user-images.githubusercontent.com/16715858/114750366-965a8980-9d5c-11eb-94e7-2b25bef117c8.png)

**Device (please complete the following information):**
 - OS: Windows

**Additional context**
Related issue: https://github.com/actions/setup-java/issues/165

**Comment by konradpabjan** [comment]
I will also add that seeing a `x32` architecture for Windows is a little bit strange. All documentation that I could find simply refers to `x32` as being `x86` and this is the first time I've come across `x32`. https://stackoverflow.com/questions/29974425/why-is-windows-32-bit-called-windows-x86-and-not-windows-x32

**Comment by johnoliver** [comment]
Using `x32` probably is a mistake, however fixing it now would be a breaking change so fixing it would probably have to wait for a major API update

**Comment by maxim-lobanov** [comment]
@johnoliver Why it is a breaking change?
As I understand, current version of API doesn't return anything if you specify `x86` and (https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/1673bb38990f4b1ae24ed365c564c4ace947263e/adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Architecture.kt#L10).

So adding some fallback for `x86` to return x32 binaries won't be a breaking change.

**Comment by johnoliver** [comment]
If you mean just make x86 synonymous with x32 for a query point of view, and just return the same binaries that a current x32 query would, then that would be possible as a non breaking change. But to modify the architectures returned in the json and change them to x86 would be breaking.

**Comment by maxim-lobanov** [comment]
If we could make x86 synonymous with x32 for now, it would be a good fix on short term.
As a long term, agree on https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/389#issuecomment-821227106 with next major release.

**Comment by johnoliver** [comment]
#392 should do this

**Comment by maxim-lobanov** [comment]
Thank you for the quick fix!

**Comment by maxim-lobanov** [comment]
Tested and it works perfectly on staging. When it will be available on PROD?

**Comment by dmitry-shibanov** [comment]
Hello @johnoliver, just gentle ping. Could you please tell us, when it will be deployed to the `PROD` ?

**Comment by johnoliver** [comment]
Its merged, thanks
