### ISSUE TITLE
Website is not showing latest HotSpot nightlies for JDK16

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-api-v3#398]
**Describe the bug**
https://adoptopenjdk.net/nightly.html?variant=openjdk16&jvmVariant=hotspot does not contain any nightlies since 8th May, and before that it was only showing Alpine. OpenJ9 ones were showing correctly up to 7th May. More recent HotSpots were correctly published to https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/tag/jdk16u-2021-05-08-12-45. Does the API need to be updated to catch the Temurin-badged binaries?

**To Reproduce**
1. Go to the nighly link shown above.
2. See that no builds other than Alpine are present

**Expected behavior**
Nightly builds for all platforms are shown

**Device (please complete the following information):**
 - OS: [e.g. Linux, MacOS, Windows, iOS, Android] Linux
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 88

**Comment by karianna** [comment]
Doesn't look like those 16 nightlies are in the https://github.com/AdoptOpenJDK/openjdk16-binaries/releases repo.  Is this simply a consequence of those pipelines not being active right now due to our Adoptium move?

**Comment by johnoliver** [comment]
The alpine issue is due to the fact that the alpines are being released with a higher version number that puts them at the top of the list, for instance the alpine from 21/04 has a version of `16.0.1+36-202104212342`, where as our latest x64 has a version of `16.0.1+9-202105072341`.

If you expand out the number of results you can then see the other results after the alpines.

**Comment by karianna** [comment]
```
00:40:38  
00:40:38  real	0m44.252s
00:40:38  user	1m31.947s
00:40:38  sys	0m9.691s
00:40:38  build.sh : 23:40:38 : Initiating build ...
00:40:38  Pulling latest tags and getting the latest update version using git fetch -q --tags --depth=1
00:40:38  NOTE: This can take quite some time!  Please be patient
00:42:31  From /home/adoptopenjdk/workspace/build-scripts/jobs/jdk16u/jdk16u-alpine-linux-x64-hotspot/workspace/./build//src
00:42:31   * branch                    HEAD       -> FETCH_HEAD
00:42:31  OpenJDK repo tag is jdk-16+36
00:42:31  Version: jdk 
00:42:31  Should have the source, I'm at /home/adoptopenjdk/workspace/build-scripts/jobs/jdk16u/jdk16u-alpine-linux-x64-hotspot/workspace/build/src
00:42:31  From /home/adoptopenjdk/workspace/build-scripts/jobs/jdk16u/jdk16u-alpine-linux-x64-hotspot/workspace/./build//src
00:42:31   * branch                    HEAD       -> FETCH_HEAD
00:42:31  OpenJDK repo tag is jdk-16+36
```

From the last build output - this seems wrong.

should be 16.0.1+9 at the very least

**Comment by karianna** [comment]
We think that git on alpine is failing to pick up the latest tag (x64 is fine).

build.sh in temurin-build repo line 855 is the start of the relevant function

**Comment by karianna** [comment]
@johnoliver has discovered the sort command on alpine from busybox is different to std sort on x64

**Comment by sxa** [comment]
> Is the command actually different or is it due to a locale setting (e.g. `LC_COLLATE` or a default)?

Answer: Yes it is. When set to `C` the values obtained on a full GNU/Linux system are the same as on Alpine

```
[sxa@sainz tmp]$ sort tags
jdk-16.0.1+9
jdk-16+36
[sxa@sainz tmp]$ LC_COLLATE=C sort tags
jdk-16+36
jdk-16.0.1+9
[sxa@sainz tmp]$ 
```

**Comment by karianna** [comment]
Fixed in temurin-build repo.
