### ISSUE TITLE
Is there a list of file types somewhere?

### ISSUE THREAD

**Issue by Osiris-Team** [AdoptOpenJDK/openjdk-api-v3#445]
JDK/JRE downloads for Linux are compressed with .tar.gz and for Windows with .zip.
Are there any other compression methods used for the other operating systems?

**Comment by karianna** [comment]
https://api.adoptopenjdk.net/q/swagger-ui/ hosts our full documentation. We provide RPMs and DEBS for Linux (note these are through package repos, not our API), pkg for Mac etc
