### ISSUE TITLE
Latest 17-ea not returned by API

### ISSUE THREAD

**Issue by codylerum** [AdoptOpenJDK/openjdk-api-v3#449]
**Describe the bug**
Using Github Actions via the setup-java action downloads the latest 17 build via the `17-ea` version. According to them it appears that the API is returning an incorrect build as the latest for JDK 17 EA.  The build is stamped 17.0.0+29.0.202101130348 (2021-01-13)

https://api.adoptopenjdk.net/v3/assets/version/%5B17.0%2C18.0%5D?architecture=x64&heap_size=normal&image_type=jdk&jvm_impl=hotspot&os=linux&page=0&page_size=10&project=jdk&release_type=ea&sort_method=DEFAULT&sort_order=DESC&vendor=adoptopenjdk

This appears to be a release labeled  +29 but created in January 2021

**To Reproduce**

Reported by the setup-java action of github actions.

https://github.com/actions/setup-java/issues/192#issuecomment-878052882

**Expected behavior**
Loads the most recent 17 ea build

**Additional context**
This problem was discovered while troubleshooting github actions failures on a project using Google Error Prone. https://github.com/google/error-prone/issues/2440#issuecomment-877727864

**Comment by johnoliver** [comment]
Looks due to an older build with an incorrect version, can exclude that build manually, but ultimately https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/jdk-2021-01-13-07-01/ should probably be removed as it is showing the wrong version

**Comment by codylerum** [comment]
@johnoliver Excluding being something that can be done by adopt, or by consumers of the the API? Not sure I'm going to be able to get the https://github.com/actions/setup-java project to manually exclude this build in their scripts.

**Comment by johnoliver** [comment]
@codylerum I mean excluding by the api, not consumers of it, #450 does this
